import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <Link to="/" className="text-brand-600 text-sm mb-6 inline-block">← Back to Home</Link>
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: July 9, 2026</p>

      <div className="prose prose-gray max-w-none space-y-6 text-gray-700">
        <h2 className="text-xl font-semibold text-gray-900">1. Service Description</h2>
        <p>LocalBoost AI provides automated marketing analysis and recommendations for local service businesses. Our service includes website analysis, SEO audits, content generation, and marketing recommendations delivered via email and web dashboard.</p>

        <h2 className="text-xl font-semibold text-gray-900">2. Payments & Pricing</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Audit fee:</strong> $49 one-time payment for a full marketing audit and 30-day action plan.</li>
          <li><strong>Future subscriptions:</strong> Monthly subscription plans ($149-$249/month) will be available at a later date for ongoing automated marketing.</li>
          <li>All payments are processed securely via Stripe. Prices are in USD.</li>
          <li>We do not offer refunds on completed audits, as the service is delivered immediately upon purchase.</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-900">3. User Responsibilities</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>You must provide accurate business information when requesting an audit.</li>
          <li>You are responsible for the website you submit for analysis. You should only submit websites you own or have permission to analyze.</li>
          <li>You may not use the service to analyze competitors' websites for the purpose of harassment or competitive abuse.</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-900">4. Intellectual Property</h2>
        <p>The audit reports, content, and recommendations generated by LocalBoost AI are provided for your internal business use. You may use, modify, and publish the generated content (social posts, emails, etc.) for your own business purposes. The LocalBoost AI platform, branding, and underlying technology remain our intellectual property.</p>

        <h2 className="text-xl font-semibold text-gray-900">5. Limitation of Liability</h2>
        <p>LocalBoost AI provides analysis and recommendations based on publicly available data and automated algorithms. We do not guarantee specific business outcomes, search engine rankings, or revenue increases. Our service is provided "as is" without warranty of any kind. We are not liable for any damages arising from the use or inability to use our service.</p>

        <h2 className="text-xl font-semibold text-gray-900">6. Service Availability</h2>
        <p>We strive for 99% uptime but do not guarantee uninterrupted service. We may temporarily suspend access for maintenance, updates, or emergency repairs. We will notify you via email when possible.</p>

        <h2 className="text-xl font-semibold text-gray-900">7. Termination</h2>
        <p>We reserve the right to terminate or suspend service for violations of these terms, fraudulent activity, or non-payment. Upon termination, you will retain access to any reports you have already purchased.</p>

        <h2 className="text-xl font-semibold text-gray-900">8. Changes to Terms</h2>
        <p>We may update these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms. We will notify users of material changes via email.</p>

        <h2 className="text-xl font-semibold text-gray-900">9. Contact</h2>
        <p>For questions about these terms, email hello@localboosts.biz.</p>
      </div>
    </div>
  );
}